name: CrashExample
targets:
  CrashExample:
    type: application
    platform: iOS
    deploymentTarget: "10.0"
    sources:
      - path: CrashExample
    dependencies:
      - framework: ../libs/crash.framework
        embed: true
    settings:
      LIBRARY_SEARCH_PATHS: "$(inherited)"
      OTHER_LDFLAGS: "$(inherited)"
      FRAMEWORK_SEARCH_PATHS: "$(inherited) $(PROJECT_DIR)/../libs/"
      CLANG_WARN_DOCUMENTATION_COMMENTS: "NO"
      TARGETED_DEVICE_FAMILY: "1,2"
      ASSETCATALOG_COMPILER_APPICON_NAME: "AppIcon"
      ENABLE_BITCODE: "NO"
      DEVELOPMENT_TEAM: "32VR5PEEGQ"
      ONLY_ACTIVE_ARCH: "NO"
      VALID_ARCHS: "arm64"
    postBuildScripts:
      - path: strip_simulator_arch.sh
        name: Strip Simulator Architectures
